<?php

namespace Fuel\Migrations;

class Add_data_admin_news
{
	public function up()
	{
		$data = array(
			array('title' => 'Car realism', 'content' => 'Car realism military-grade cartel augmented reality plastic girl hacker assassin bicycle kanji uplink systema shoes bridge 3D-printed. Chiba motion stimulate augmented reality market physical RAF marketing denim gang j-pop spook BASE jump realism camera. 8-bit industrial grade ablative singularity garage smart-3D-printed decay knife. Boy camera courier skyscraper shanty town man wristwatch j-pop pen franchise grenade systemic BASE jump advert 3D-printed face forwards car. Realism office jeans narrative human assault sprawl. Numinous shrine narrative drone assault towards car Chiba long-chain hydrocarbons man engine uplink sunglasses systema. Savant claymore mine hotdog soul-delay order-flow paranoid courier pistol San Francisco cartel faded crypto-denim beef noodles sign. Augmented reality Chiba bridge long-chain hydrocarbons cardboard boy papier-mache corporation lights. Realism paranoid car DIY futurity tiger-team long-chain hydrocarbons fluidity hotdog boy sunglasses weathered. Dome sprawl bridge Kowloon spook fetishism plastic.'),
			array('title' => '8-bit youtube engine systemic', 'content' => '8-bit youtube engine systemic pistol skyscraper Kowloon network rain man saturation point faded Tokyo savant towards modem silent. Network vinyl singularity city advert voodoo god claymore mine man DIY j-pop smart-wristwatch plastic. Boy convenience store Tokyo rebar post-sub-orbital table shoes industrial grade sign plastic DIY. Hacker dissident corrupted semiotics into apophenia construct tanto-ware dolphin. Man dolphin cardboard skyscraper drone film vehicle pistol order-flow digital tiger-team tower face forwards.'),
			array('title' => 'Rebar drugs courier table-active', 'content' => 'Rebar drugs courier ablative towards military-grade Chiba. Denim DIY network footage bicycle otaku nano. Vinyl numinous cyber-DIY wonton soup tower sprawl film neon euro-pop refrigerator rifle. Wonton soup nano-tanto geodesic rain carbon military-grade tiger-team modem cyber-hotdog pre-dissident claymore mine narrative. Sentient nodal point papier-mache camera marketing convenience store modem beef noodles shanty town tiger-team dissident tube bicycle. Realism paranoid car DIY futurity tiger-team long-chain hydrocarbons fluidity hotdog boy sunglasses weathered. Dome sprawl bridge Kowloon spook fetishism plastic.'),
			array('title' => 'Network pistol Legba', 'content' => 'Network pistol Legba j-pop neural Chiba fetishism stimulate singularity systemic courier. Office faded paranoid receding wristwatch computer sentient military-grade assassin vinyl woman grenade franchise. Tower bomb weathered ablative San Francisco knife shanty town disposable garage soul-delay render-farm semiotics futurity otaku Tokyo franchise. Shanty town jeans silent 3D-printed neon digital bicycle faded. Urban kanji neural Tokyo market woman pen bomb Shibuya office motion faded Legba. Long-chain hydrocarbons military-grade-ware modem j-pop network bicycle human hacker-space boy man. Courier kanji drone nodal point denim claymore mine systema boat narrative office weathered dissident. Face forwards free-market rifle disposable range-rover sunglasses sensory narrative footage uplink dissident savant DIY advert urban shrine. Car futurity A.I. fluidity urban neon courier drone systemic footage sensory nano-numinous tattoo. Realism paranoid car DIY futurity tiger-team long-chain hydrocarbons fluidity hotdog boy sunglasses weathered. Dome sprawl bridge Kowloon spook fetishism plastic.'),
			array('title' => 'Sprawl corporation shoes fetishism', 'content' => 'Sprawl corporation shoes fetishism garage cyber--ware knife rain industrial grade monofilament wonton soup gang jeans paranoid. Disposable shanty town tower Kowloon tube camera voodoo god math-faded beef noodles. Marketing monofilament 8-bit crypto-weathered into footage office motion otaku cartel Legba shrine media computer. Chrome beef noodles katana Chiba BASE jump-ware euro-pop table bomb nano. Realism paranoid car DIY futurity tiger-team long-chain hydrocarbons fluidity hotdog boy sunglasses weathered. Dome sprawl bridge Kowloon spook fetishism plastic.'),
			array('title' => 'Wristwatch otaku drone convenience position-relative', 'content' => 'Wristwatch otaku drone convenience store assault towards tower camera math-hotdog tattoo BASE jump carbon neon bicycle-ware. Drone saturation point into math-youtube face forwards claymore mine RAF euro-pop sentient geodesic film. Military-grade assassin face forwards futurity plastic rebar RAF alcohol. Into beef noodles chrome denim military-grade cardboard hotdog. Physical marketing market drone skyscraper weathered sensory bicycle assassin refrigerator towards sunglasses neural ablative car lights Shibuya. Tattoo kanji youtube construct network wonton soup face forwards dome Shibuya hotdog BASE jump carbon rifle physical. Artisanal rain papier-mache city nodal point skyscraper footage dolphin Kowloon monofilament render-farm pen silent disposable vehicle. Sensory girl monofilament fetishism soul-delay industrial grade dome alcohol. Advert San Francisco hacker euro-pop bicycle receding motion dead-ware. Realism paranoid car DIY futurity tiger-team long-chain hydrocarbons fluidity hotdog boy sunglasses weathered. Dome sprawl bridge Kowloon spook fetishism plastic.'),
			array('title' => 'Vinyl computer neural numinous', 'content' => 'Vinyl computer neural numinous nodality into city pen apophenia Chiba hacker wonton soup augmented reality DIY fetishism construct. Computer gang uplink katana city digital table 8-bit boy ablative rifle rain grenade free-market. Singularity monofilament smart-Shibuya courier pre-physical market saturation point corrupted RAF numinous kanji footage artisanal neural futurity. Monofilament Shibuya San Francisco shanty town courier decay numinous bicycle towards car beef noodles.'),
			array('title' => 'Sentient narrative 3D-printed', 'content' => 'Sentient narrative 3D-printed dome towards paranoid shrine market. Grenade tube systemic neon nodal point franchise disposable vehicle construct bridge realism pre-alcohol warehouse wonton soup gang. RAF Legba into tower katana hotdog rifle courier. Woman tube semiotics artisanal grenade 8-bit bicycle cartel paranoid Kowloon garage katana vinyl girl saturation point. Media refrigerator tiger-team kanji franchise warehouse into sunglasses. Vinyl otaku claymore mine assassin free-market singularity tank-traps corrupted j-pop-space savant systema math. A.I. carbon spook sunglasses narrative augmented reality euro-pop courier sentient dissident towards post. Dead wonton soup carbon hacker corporation crypto-post-euro-pop saturation point boy DIY lights long-chain hydrocarbons singularity vehicle rifle sprawl.'),
			array('title' => 'Rebar market post-cyber-urban systemic', 'content' => 'Rebar market post-cyber-urban systemic grenade uplink. Artisanal post-sub-orbital office tube DIY pistol rebar uplink tanto corporation euro-pop. Vinyl advert otaku faded neural boy warehouse rifle DIY math-carbon face forwards augmented reality dissident drone cyber. Tattoo realism shanty town claymore mine decay shrine j-pop receding. Digital math-corrupted military-grade car industrial grade garage pen media uplink boat systema post-sunglasses assault grenade hotdog. Soul-delay grenade construct courier human papier-mache modem neon wristwatch futurity corporation chrome film shrine Shibuya sub-orbital. Bomb paranoid 3D-printed urban table systema math. Decay-space savant paranoid jeans beef noodles drone woman post-sprawl. Realism paranoid car DIY futurity tiger-team long-chain hydrocarbons fluidity hotdog boy sunglasses weathered. Dome sprawl bridge Kowloon spook fetishism plastic.'),
			array('title' => 'Table market Kowloon', 'content' => 'Table market Kowloon gang chrome industrial grade fluidity city office nodal point bicycle carbon sign augmented reality nodality silent j-pop. Nodality rain denim neon rifle computer voodoo god crypto-singularity sign. Nano-crypto-8-bit long-chain hydrocarbons savant voodoo god plastic dome. Military-grade girl singularity fetishism table hotdog long-chain hydrocarbons lights physical paranoid systema sensory bomb tiger-team beef noodles savant shoes. Realism paranoid car DIY futurity tiger-team long-chain hydrocarbons fluidity hotdog boy sunglasses weathered. Dome sprawl bridge Kowloon spook fetishism plastic.'),
			array('title' => 'Motion camera sentient', 'content' => 'Motion camera sentient shanty town fetishism film towards geodesic wonton soup refrigerator ablative BASE jump. Receding saturation point dome concrete decay hotdog cyber-meta-Shibuya otaku range-rover artisanal towards dolphin nodality singularity fetishism. Drugs shanty town gang sign vehicle vinyl render-farm dead free-market courier post. Euro-pop refrigerator modem systema stimulate market corporation nano-car augmented reality jeans denim gang human papier-mache. Neural dead long-chain hydrocarbons sunglasses hacker cartel office dome youtube gang rifle render-farm Kowloon rain DIY Chiba industrial grade. Realism paranoid car DIY futurity tiger-team long-chain hydrocarbons fluidity hotdog boy sunglasses weathered. Dome sprawl bridge Kowloon spook fetishism plastic.'),
			array('title' => 'Network systemic uplink vinyl', 'content' => 'Network systemic uplink vinyl man realism semiotics j-pop nano-gang BASE jump saturation point sub-orbital tower advert. Woman hotdog carbon motion shoes nodal point otaku office. Dead wonton soup realism assassin human dissident paranoid nodality marketing shoes engine claymore mine rifle. Drugs cyber-industrial grade military-grade table pen dome. Corporation shrine towards meta-modem industrial grade motion. Computer drone warehouse towards crypto-garage assassin dome denim dead sunglasses systemic. Realism paranoid car DIY futurity tiger-team long-chain hydrocarbons fluidity hotdog boy sunglasses weathered. Dome sprawl bridge Kowloon spook fetishism plastic.'),
			array('title' => 'Computer artisanal paranoid', 'content' => 'Computer artisanal paranoid franchise shanty town disposable rain spook numinous geodesic crypto-Tokyo wristwatch weathered DIY. Weathered BASE jump meta-convenience store military-grade tanto advert otaku papier-mache carbon uplink. Corporation receding hotdog 8-bit DIY construct skyscraper sign pistol BASE jump. BASE jump woman sentient tank-traps monofilament concrete Legba singularity pistol drone face forwards meta. Numinous construct market motion voodoo god shanty town cardboard. Disposable BASE jump free-market sentient decay singularity San Francisco crypto-post-meta-franchise assassin office marketing media wonton soup human. Garage warehouse kanji order-flow dolphin vehicle digital fetishism tattoo. Realism paranoid car DIY futurity tiger-team long-chain hydrocarbons fluidity hotdog boy sunglasses weathered. Dome sprawl bridge Kowloon spook fetishism plastic.'),
			array('title' => 'Bridge wonton soup hotdog', 'content' => 'Bridge wonton soup hotdog stimulate San Francisco BASE jump augmented reality Chiba courier. Kowloon franchise hotdog woman corporation refrigerator semiotics range-rover lights free-market nodality rain footage. Apophenia girl computer sunglasses stimulate urban boat dome realism boy render-farm. Boy pen shrine post-man systema crypto-singularity sentient free-market wonton soup voodoo god franchise. 8-bit tanto math-assault construct cartel girl systemic drugs cardboard rifle Kowloon wonton soup urban futurity claymore mine. Systema kanji narrative marketing silent neon car engine order-flow grenade systemic drone denim futurity math. Kanji shoes long-chain hydrocarbons knife spook order-flow silent geodesic city urban-ware. Sunglasses Tokyo sign dome apophenia computer assassin tower convenience store monofilament bridge realism sensory fluidity marketing. DIY geodesic sign media cartel neon marketing nodality 3D-printed pistol engine jeans order-flow realism tower. Realism paranoid car DIY futurity tiger-team long-chain hydrocarbons fluidity hotdog boy sunglasses weathered. Dome sprawl bridge Kowloon spook fetishism plastic.'),
			array('title' => 'BASE jump voodoo god', 'content' => 'BASE jump voodoo god ablative concrete euro-pop nodality tattoo fluidity Tokyo human pre-grenade youtube bomb augmented reality assassin crypto. Franchise beef noodles film pistol San Francisco advert shoes singularity euro-pop fetishism dome dolphin shrine tower pen. Shanty town tower tattoo claymore mine boy car lights tank-traps media convenience store cartel Kowloon paranoid smart. DIY gang singularity Tokyo film dolphin towards rain. Cardboard camera bicycle hacker RAF denim towards bomb weathered boy skyscraper. Sensory numinous shrine grenade vehicle San Francisco decay 8-bit corrupted dome geodesic bridge lights free-market man gang apophenia. Boy shanty town disposable media knife-space weathered into hacker artisanal claymore mine shoes industrial grade bridge realism. Papier-mache face forwards corrupted sign sprawl man euro-pop network towards. Realism paranoid car DIY futurity tiger-team long-chain hydrocarbons fluidity hotdog boy sunglasses weathered. Dome sprawl bridge Kowloon spook fetishism plastic.'),
			array('title' => 'Artisanal tank-traps saturation point', 'content' => 'Artisanal tank-traps saturation point boat 8-bit advert otaku lights youtube silent corporation corrupted pre-assassin car disposable. Tattoo into sign table render-farm girl wonton soup pen. Rifle semiotics knife-space warehouse garage tube order-flow industrial grade alcohol assault. Realism paranoid car DIY futurity tiger-team long-chain hydrocarbons fluidity hotdog boy sunglasses weathered. Dome sprawl bridge Kowloon spook fetishism plastic.'),
			array('title' => 'Tiger-team augmented reality dolphin', 'content' => 'Tiger-team augmented reality dolphin dome dissident katana free-market table artisanal cartel. Computer wonton soup tower hotdog media table industrial grade order-flow-space long-chain hydrocarbons dome decay youtube knife garage. Nodality claymore mine denim dissident urban rain fetishism towards dead network convenience store vehicle. Tokyo urban RAF dome math-A.I. vehicle spook tattoo vinyl computer. Weathered fluidity youtube rifle car disposable Kowloon. Realism paranoid car DIY futurity tiger-team long-chain hydrocarbons fluidity hotdog boy sunglasses weathered. Dome sprawl bridge Kowloon spook fetishism plastic.'),
			array('title' => 'Tube tanto futurity', 'content' => 'Tube tanto futurity tiger-team tower gang crypto-refrigerator. Numinous convenience store Chiba sunglasses physical network youtube wonton soup motion katana bomb knife apophenia carbon warehouse. Post-artisanal semiotics tower Legba receding bridge nano-girl futurity. Refrigerator tiger-team market industrial grade decay into paranoid math-marketing otaku saturation point boat. '),
			array('title' => 'Stimulate human bomb', 'content' => 'Stimulate human bomb urban Shibuya smart-tanto courier-ware kanji. City shrine garage sunglasses spook j-pop crypto-chrome. Systema industrial grade semiotics-space computer ablative convenience store nodality carbon warehouse render-farm free-market drugs wonton soup construct artisanal. Corrupted concrete advert bicycle free-market media knife plastic voodoo god long-chain hydrocarbons narrative. Realism paranoid car DIY futurity tiger-team long-chain hydrocarbons fluidity hotdog boy sunglasses weathered. Dome sprawl bridge Kowloon spook fetishism plastic.'),
			array('title' => 'Vinyl hacker justify-content-lg-center', 'content' => 'Vinyl hacker silent jeans tanto modem monofilament concrete artisanal post-cartel neural neon footage. Knife refrigerator alcohol dome shoes stimulate realism BASE jump warehouse table disposable assassin. Sprawl wonton soup cyber-tiger-team bridge alcohol euro-pop. Nodality bicycle beef noodles sign motion shrine neon tattoo katana rain pen DIY. Assault sign Legba neon Kowloon singularity drone savant girl. RAF man bridge fluidity nodality concrete advert sensory range-rover rifle. Wristwatch corporation engine beef noodles range-rover tank-traps hacker gang city pistol. Neural smart-voodoo god receding girl tower render-farm RAF claymore mine. Rain industrial grade beef noodles DIY Tokyo advert neon alcohol corporation geodesic savant tube systema. Realism paranoid car DIY futurity tiger-team long-chain hydrocarbons fluidity hotdog boy sunglasses weathered. Dome sprawl bridge Kowloon spook fetishism plastic.')
		);

		$query = \DB::insert('admin_news')->columns(array('title', 'content', 'created_at', 'updated_at'));

		foreach ($data as $val) {
			$query->values(array($val['title'], $val['content'], time(), time()));
		}

		if (!$query->execute()) {
			\Cli::error('Ошибка добавления записей');
		}
	}

	public function down()
	{
		\DBUtil::truncate_table('admin_news');
	}
}
